// Generated by CoffeeScript 1.8.0
(function() {
  /*
      index
      /explore
   */
  exports.index = function(req, res) {
      res.render("index", {
          //loopIndex: true,
          //items: items,
          //users: users,
          //isLogin: userHelper.isLogin(req, res)
      });
  };

}).call(this);

//# sourceMappingURL=home.js.map
