// Generated by CoffeeScript 1.8.0
(function() {
  var userBll = require('../Bll/userBll'), setSession;
  /*
  mvc配置
  @type {{}}
   */
  exports.$mvcConfig = {
    route: {
      index: {
        path: "/user/:id",
        httpVerbs: ["get"]
      }
    }
  };
  /*
      注册
      @param email
      @param password
   */
  exports.register_GET_POST = function(req, res) {
    var user;
    if (req.method === "POST") {
      user = {
        name: req.body.name,
        email: req.body.email,
        password: req.body.password,
        resNum: 0,
        ansNum: 0,
        score: 0
      };
      return userBll.register(user, function(err, result) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else {
          setSession(req, result[0]);
          return res.send({
            code: 0,
            message: 'true',
            user: result[0]
          })
        }
      });
    } else {
      return res.send({
        code: 1,
        message: 'not found'
      })
    }
  };


  /*
      登录
      @param email
      @param password
   */

  exports.login_GET_POST = function(req, res) {
    var user;
    if (req.method === "POST") {
      user = {
        email: req.body.userName,
        password: req.body.pwd
      };
      return userBll.login(user, function(err, result) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else if (!result) {
          return res.send({
            code: 1,
            message: '用户不存在,请注册后登录'
          });
        } else {
          setSession(req, result);
          return res.send({
            code: 0,
            message: 'ok',
            result: result
          });
        }
      });
    }
  };


  /*获取用户信息
      退出登录
   */

  exports.signOut = function(req, res) {
    res.session.clear();
    return res.redirect("/explore");
  };


  /*
  	获取用户信息
   */

  exports.getUserInfo = function(req, res) {
    var userId;
    userId = req.query.id || req.session.userId;
    return userBll.getUserInfo(userId, function(err, user) {
      if (err) {
        return res.send({
          code: 1,
          message: err.message
        });
      } else {
        return res.send({
          code: 0,
          message: "ok",
          user: user
        });
      }
    });
  };

  /*
   创建session
   */

  setSession = function(req, result) {
    req.session.userId = result._id.toString();
    req.session.userName = result.name;
    req.session.userEmail = result.email;
    return req.session.userAvatar = result.avatar;
  };
  /*
  	用户主页
   */

  exports.index = function(req, res) {
   res.send('this is index');
  };

}).call(this);

//# sourceMappingURL=user.js.map
