// Generated by CoffeeScript 1.8.0
(function () {
    var userBll = require('../Bll/userBll'), setSession;

    exports.router = function (app) {
        /*
         注册
         @param email
         @param password
         */
        app.post('/user/register', function (req, res, next) {
            var user;
            user = {
                name: req.body.name,
                password: req.body.password,
                resNum: 0,
                ansNum: 0,
                score: 0
            };
            userBll.register(user, function (err, result) {
                if (err) {
                    return res.send({
                        code: 1,
                        message: err.message
                    });
                } else {
                    setSession(req, result[0]);
                    res.send({
                        code: 0,
                        message: 'true',
                        user: result[0]
                    })
                }
            });
        });


        /*
         登录
         @param email
         @param password
         */


        app.post('/user/login', function (req, res, next) {
            var user;
            user = {
                name: req.body.name,
                password: req.body.password
            };
            return userBll.login(user, function (err, result) {
                if (err) {
                    return res.send({
                        code: 1,
                        message: err.message
                    });
                } else if (!result) {
                    return res.send({
                        code: 1,
                        message: '账号与密码不匹配,请重新输入'
                    });
                } else {
                    setSession(req, result);
                    return res.send({
                        code: 0,
                        message: 'ok',
                        user: {
                            userId: result._id.toString(),
                            name: result.name
                        }
                    });
                }
            });
        });

        /**
         * 判断是否登录
         * @param req
         * @param res
         */
        app.get('/user/isLogin', function (req, res, next) {
            if (req.session.get('userId')) {
                res.send({
                    code: 0,
                    message: 'true',
                    user: {
                        userId: req.session.get('userId'),
                        nickname: req.session.get('userName')
                    }
                });
            } else {
                res.send({
                    code: 1,
                    message: 'false'
                });
            }
        });

        /*
         获取用户信息
         */
        app.get('/user/getUserInfo', function (req, res, next) {
            var userId;
            userId = req.query.id || req.session.get('userId');
            return userBll.getUserInfo(userId, function (err, user) {
                if (err) {
                    return res.send({
                        code: 1,
                        message: err.message
                    });
                } else {
                    return res.send({
                        code: 0,
                        message: "ok",
                        user: user
                    });
                }
            });
        });

        /**
         * 退出登录
         */
        app.get('/user/signOut', function (req, res, next) {
            req.session.clear(function (err) {
                if (!err) {
                    res.redirect("/");
                }
            });
        });

        app.get('/mobile/user/signOut', function (req, res, next) {
            req.session.clear(function (err) {
                if (!err) {
                    res.send({
                        code: 0,
                        message: '退出成功'
                    });
                }
            });
        })
    };


    /*
     创建session
     */

    setSession = function (req, result) {
        req.session.set('userId', result._id.toString());
        req.session.set('userName', result.name);
        req.session.set('userEmail', result.email);
        req.session.set('userAvatar', result.avatar);
    };

}).call(this);

//# sourceMappingURL=user.js.map
