// Generated by CoffeeScript 1.8.0
(function() {
  var userBll = require('../Bll/userBll'), setSession;

  exports.router = function(app) {
    /*
     注册
     @param email
     @param password
     */
    app.get('/user/register',function(req, res, next) {
      res.send({
        code: 1,
        message: 'register is not found'
      })
    });
    app.post('/user/register',function(req, res, next) {
      var user;
      user = {
        name: req.body.name,
        password: req.body.password,
        resNum: 0,
        ansNum: 0,
        score: 0
      };
      userBll.register(user, function(err, result) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else {
          setSession(req, result[0]);
          res.send({
            code: 0,
            message: 'true',
            user: result[0]
          })
        }
      });
    });


    /*
     登录
     @param email
     @param password
     */
    app.get('/user/login',function(req, res, next) {
      res.send({
        code: 1,
        message: 'login is not found'
      })
    });

    app.post('/user/login',function(req, res, next) {
      var user;
      user = {
        name: req.body.name,
        password: req.body.password
      };
      return userBll.login(user, function(err, result) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else if (!result) {
          return res.send({
            code: 1,
            message: '用户不存在,请注册后登录'
          });
        } else {
          setSession(req, result);
          console.log(req.session);
          return res.send({
            code: 0,
            message: 'ok',
            user: {
              userId: result._id.toString(),
              name: result.name
            }
          });
        }
      });
    });

    /**
     * 判断是否登录
     * @param req
     * @param res
     */
    app.get('/user/isLogin', function(req, res, next) {
      if(req.session.userId) {
        res.send({
          code: 0,
          message: 'true',
          user: {
            userId: res.session.userId,
            nickname: res.session.nickname
          }
        });
      }else {
        res.send({
          code: 1,
          message: 'false'
        });
      }
    });

    /*
     获取用户信息
     */
    app.get('/user/getUserInfo', function(req, res, next) {
      var userId;
      userId = req.query.id || req.session.userId;
      return userBll.getUserInfo(userId, function(err, user) {
        if (err) {
          return res.send({
            code: 1,
            message: err.message
          });
        } else {
          return res.send({
            code: 0,
            message: "ok",
            user: user
          });
        }
      });
    })
  };



  /*获取用户信息
      退出登录
   */
  exports.signOut = function(req, res) {
    res.session.clear();
    return res.redirect("/explore");
  };


  /*
   创建session
   */

  setSession = function(req, result) {
    req.session.userId = result._id.toString();
    req.session.userName = result.name;
    req.session.userEmail = result.email;
    req.session.userAvatar = result.avatar;
  };

}).call(this);

//# sourceMappingURL=user.js.map
